name: majestic_ui
description: A Shadcn equivalent for Flutter where you can quickly install widgets onto your projects without having to add them as a dependency. This allows flexible customizations and faster code availability.
version: 1.0.5
repository: https://github.com/Ronak99/majesticui-cli

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  args: ^2.6.0
  path: ^1.9.1
  chalkdart: ^2.3.2
  interact_cli: ^2.4.0
  enough_ascii_art: ^1.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  majestic_ui: majestic_ui
